### PR TITLE
Label to show on mouse hover

### PR DESCRIPTION
**Pull request by alyst**
This PR adds support for labels that are shown when mouse hovers over the points in scatterplot. It thus allows annotating the clouds with thousands of points. The label can be any HTML snippet and it's displayed by overlaying HTML over the three.js scene.  

In addition, the PR updates d3 and three.js to the latest versions, switches to OrbitControls.js for navigation + a few other enhancements. ATM the sprite-based cloud is not supported, but there should be a workaround.

### CODE REVIEW

**Comment by bwlewis** [comment]
Oh man, this is awesome. I didn't know about orbitcontrols! I'll go though this carefully today and then merge.

**Comment by bwlewis** [comment]
I'm going to work on this a little bit. The changes have broken the canvas renderer, which is an important fallback to have. Rendering quality is also a bit low for some reason, even on openGL for my machine. I'll try to fix these few issues over the next day or so. Otherwise, quite awesome!

**Comment by alyst** [comment]
@bwlewis Thanks for looking into PR! Clearly it's not finished, I wanted to publish it that early, so that we can define proper solutions for the issues you mentioned.
It would be nice to support PointCloud directly in the canvas renderer. That way we would be able to handle the whole scene using the same code path for all renderers.
I'm not sure what specific rendering issues you mean, but for huge point clouds we might need to sacrifice the quality over speed. It would be nice, if that could be controlled in the options.

**Comment by bwlewis** [comment]
The webgl rendering issues aren't your fault. I noticed that the png images are rendered as opaque squares in webgl mode, even though they have transparent backgrounds (set size=10 or something to see this, it looks bad). I need to fix that. Or maybe I should just get rid of the 'webgl' mode using sprites in favor of the buffered point cloud (webgl-buffered), which looks different but OK and has great performance. But the hover text isn't working in the buffered geometry yet.

I'm not sure that the pointcloud is ever going to work in canvas, (many threejs examples don't for example). But canvas is still really important to make work (stable rstudio needs it for now, as do various browsers that have trouble with webgl). I think having two code paths of variable performance/quality is OK if a bit of a pain. But you're right, the three code paths I have in there now is a bit much.

I'll try to isolate the cause of the canvas issues and fix it, and make your hover work in both canvas and the buffered point cloud. I think the hover addition is really important...

**Comment by bwlewis** [comment]
Dear Alexey, I've incorporated many of your ideas in to the latest commits. I couldn't merge this directly because I ended up also simplifying the WebGL rendering to only use Buffered methods for performance.

But! You taught me how to do the hover labels, and those are now integrated for both WebGL and Canvas! Thanks! I have not yet got orbit.js working all around, so that's not in there yet.

**Comment by alyst** [comment]
That's great, thank you!

**Pull request closed without merging**
